### PR TITLE
Fixed bug where NLogLogProvider performs reflections for all log…

### PR DESCRIPTION
**Pull request by snakefoot**
Fixes performance bug introduced with #200 (Performs reflection on every logevent. Performs reflection on every logger-object-creation).

Updates NLog-test-project dependency to NLog 4.6 (Changed the NLog-test-project to use MDLC + NDLC instead). Handling the breaking change introduced in #181

This PR is not a breaking change.

### CODE REVIEW

**Comment by snakefoot** [comment]
@damianh Ready for review. Maybe also resolve #179 + #180

**Comment by snakefoot** [comment]
@damianh Found that #200 by @jesperl introduced reflection-logic when ever logging an event:

https://github.com/damianh/LibLog/blob/74e53f70bb7942a6953a2f8460e5755549b0e4eb/src/LibLog/LogProviders/NLogLogProvider.cs#L198

It also performs reflection logic in constructor when ever creating a Logger-object:

https://github.com/damianh/LibLog/blob/74e53f70bb7942a6953a2f8460e5755549b0e4eb/src/LibLog/LogProviders/NLogLogProvider.cs#L191-L195

I have now fixed both issues. Removing memory allocation issues and performance hit.

**Comment by snakefoot** [comment]
@damianh Found that #200 by @jesperll introduced reflection-logic when ever logging an event:

https://github.com/damianh/LibLog/blob/74e53f70bb7942a6953a2f8460e5755549b0e4eb/src/LibLog/LogProviders/NLogLogProvider.cs#L198

It also performs reflection logic in constructor when ever creating a Logger-object:

https://github.com/damianh/LibLog/blob/74e53f70bb7942a6953a2f8460e5755549b0e4eb/src/LibLog/LogProviders/NLogLogProvider.cs#L191-L195

I have now fixed both issues. Removing memory allocation issues and performance hit.

**Comment by 304NotModified** [comment]
Polite bump @damianh

**Comment by snakefoot** [comment]
@damianh Another polite bump. Would be nice to fix the regression introduced with LibLog ver. 5.0.5

**Comment by snakefoot** [comment]
@damianh Yet another ping pong

**Comment by snakefoot** [comment]
@damianh Another polite bump to have this bug-fix released and merged.

**Comment by 304NotModified** [comment]
@damianh please accept this PR. Snakefoot is one of the core contributors of NLog and so you could merge this one with confidence.

If this PR need some changes, please also let us know.

**Comment by snakefoot** [comment]
@damianh How is the calendar looking? Any room available for merging this PR?

**Comment by damianh** [comment]
Thanks for PR and patience. Will release this asap.

**Comment by snakefoot** [comment]
Thank you for merging. Looking forward to the final and last release of LibLog.

**Comment by snakefoot** [comment]
Created #271 as a bonus PR to close down a few more issues before version 5.0.7

**Pull request merged**
