### PR TITLE
Pass parameters to logger

### PR DESCRIPTION
**Pull request by tikinoa**
Love the project.   Minor fix to pass format parameters to the logger.

### CODE REVIEW

**Comment by damianh** [comment]
Good stuff, thx!

**Comment by damianh** [comment]
@tikinoa Did you just create an account to fix this? If so awesome :smile:

**Comment by tikinoa** [comment]
Yeah, my first actual github pull request.   I’ve been programming/architect for 2 decades, but haven’t gotten involved in any open source projects.

**Comment by damianh** [comment]
beta2 with this fix is on nuget.org.

**Pull request merged**
