### PR TITLE
Add callsite support for NLogLogProvider, fix issue #102

### PR DESCRIPTION
**Pull request by yyjdelete**

### CODE REVIEW

**Comment by Nicholi** [comment]
Doesn't seem to actually pull out the correct call site though. Exact same code from my bug request https://github.com/damianh/LibLog/issues/102

```
2016-09-23 16:10:50.6885  INFO   1 ConsoleApplication11.Logging.LogExtensions.Info Hi LibLog
2016-09-23 16:10:50.7345  INFO   1 ConsoleApplication11.Program.Main Hi CommonLog
2016-09-23 16:10:50.7345  INFO   1 ConsoleApplication11.Program.Main Hi NLogLogger
```

**Comment by yyjdelete** [comment]
Fixed when used with LogExtensions

**Comment by Nicholi** [comment]
Cool thanks for this.

**Comment by damianh** [comment]
Thanks for the contrib, looks good. Apologies for not getting to is sooner.

**Pull request merged**
