### PR TITLE
Add support for merged assemblies.

### PR DESCRIPTION
**Pull request by kll**
When using LibLog with assemblies that have been merged together with [ILRepack](https://github.com/gluck/il-repack) the `Type.GetType()` calls fail because of the assembly qualified type names that no longer match. The fix is just to fall back on the plain type name without the assembly portion when the first attempt returns null. Rather than change all the `Type.GetType()` calls I added static functions in the base to do it.

I couldn't figure out a way to correctly unit test everything from a merged assembly easily. I'm using a build based on this and it is indeed working and all the existing unit tests pass.

### CODE REVIEW

**Comment by damianh** [comment]
Seems like a reasonable request and PR. Am wondering if there are any edge cases that could trip this up?

**Comment by damianh** [comment]
Can think of any so will merge and ship. Am going on your assesment that it is working for you in production ;)

**Comment by kll** [comment]
Technically not all the way to "Production", but definitely in our "Production Like" test environment. :)

Any chance of an official nuget release soon?

**Comment by damianh** [comment]
On nuget.org.

**Comment by kll** [comment]
Sorry to keep poking, but any chance of a non pre-release version on nuget.org? :)

**Comment by snakefoot** [comment]
@damianh There is an official LibLog 5.0.7 release note:

https://github.com/damianh/LibLog/releases/tag/v5.0.7

But the 5.0.7 release on nuget includes build number (Making it a pre-release build):

https://www.nuget.org/packages/LibLog/5.0.7-build.575

**Pull request merged**
