### PR TITLE
LibLog - Support NLog callsite without always creating StackTrace

### LINKED ISSUE #129: LibLog performance
Following discussion in https://github.com/npgsql/npgsql/issues/1438, I've whipped up [a minimal benchmark with BenchmarkDotNet](https://github.com/roji/LibLogBenchmarks) that compares raw NLog logging to LibLog+NLog, with a null target. The idea is to compare performance when logging to an enabled and a disabled loglevel (results at the bottom) - feel free to look at my scenarios.

As always with performance, whether the results are acceptable or not is going to depend on the consuming application. However, 16us for a single logging call seems like a lot. A likely culprit is the stack frame walk discussed in #97. In addition, while the use of dynamic makes the code elegant, it likely adds another unnecessary performance hit vs. using only reflection.

Again, I'm not sure what the performance goals of this library is, so you might choose to disregard this entirely.

``` ini

BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6700HQ CPU 2.60GHz, ProcessorCount=8
Frequency=2531248 Hz, Resolution=395.0620 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0


```
 Method | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   **NLog** |      **False** |    **193.1667 ns** |   **1.9550 ns** |   **1.00** |          **0.00** | **0.0386** |     **160 B** |
 LibLog |      False | 16,002.9138 ns | 177.6954 ns |  82.85 |          1.20 | 0.4232 |   3.87 kB |
   **NLog** |       **True** |      **2.3487 ns** |   **0.0220 ns** |   **1.00** |          **0.00** |      **-** |       **0 B** |
 LibLog |       True |     52.7087 ns |   0.6893 ns |  22.44 |          0.35 | 0.0135 |      52 B |

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to fix  #129

Maybe same idea can be applied to log4net, so #97 can also be fixed.

### CODE REVIEW

**Comment by snakefoot** [comment]
@megakid Would you mind running your performance test using these code-changes ?

**Comment by snakefoot** [comment]
@Shachar1 & @phatcher  Would you mind testing if the callsite is working for you with these code-changes?

**Comment by snakefoot** [comment]
**--When logging enabled--**

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog | ${callsite} ${message} |      False | 16,976.2954 ns |  74.2730 ns |   1.00 |          0.00 | 0.9644 |   5.18 kB |
 LibLog | ${callsite} ${message} |      False | 29,961.0324 ns | 154.2613 ns |   1.76 |          0.01 | 0.8057 |    6.9 kB |

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog |             ${message} |      False |    307.9269 ns |   1.7811 ns |   1.00 |          0.00 | 0.0820 |     296 B |
 LibLog |             ${message} |      False |  3,028.6365 ns |  11.6365 ns |   9.84 |          0.07 | 0.0885 |     844 B |

Without callsite then LibLog is still 10 times slower than raw NLog, but no longer 100 times slower :)

**--When logging disabled--**


 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog | ${callsite} ${message} |       True |      1.8350 ns |   0.0084 ns |   1.00 |          0.00 |      - |       0 B |
 LibLog | ${callsite} ${message} |       True |     64.7354 ns |   0.2459 ns |  35.28 |          0.20 | 0.0132 |      52 B |

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog |             ${message} |       True |      1.8285 ns |   0.0136 ns |   1.00 |          0.00 |      - |       0 B |
 LibLog |             ${message} |       True |     66.3291 ns |   1.4205 ns |  36.28 |          0.79 | 0.0129 |      52 B

**Comment by snakefoot** [comment]
Discovered that the LibLog overhead is still high, and made some improvements:

**--When logging enabled--**

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog | ${callsite} ${message} |      False | 17,198.6413 ns | 260.0332 ns |   1.00 |          0.00 | 0.9806 |   5.18 kB |
 LibLog | ${callsite} ${message} |      False | 27,091.9958 ns | 286.4725 ns |   1.58 |          0.03 | 0.7731 |   6.56 kB |

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog |             ${message} |      False |    320.1067 ns |   5.1049 ns |   1.00 |          0.00 | 0.0818 |     296 B |
 LibLog |             ${message} |      False |  1,647.0836 ns |  15.3561 ns |   5.15 |          0.09 | 0.1033 |     604 B |

Without callsite then LibLog is still 5 times slower than raw NLog, but no longer 100 times slower :)

**--When logging disabled--**


 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog | ${callsite} ${message} |       True |      1.8676 ns |   0.0237 ns |   1.00 |          0.00 |      - |       0 B |
 LibLog | ${callsite} ${message} |       True |     66.9068 ns |   0.6724 ns |  35.83 |          0.56 | 0.0135 |      52 B |

 Method |                 Layout | IsDisabled |           Mean |      StdDev | Scaled | Scaled-StdDev |  Gen 0 | Allocated |
------- |----------------------- |----------- |--------------- |------------ |------- |-------------- |------- |---------- |
   NLog |             ${message} |       True |      1.8812 ns |   0.0186 ns |   1.00 |          0.00 |      - |       0 B |
 LibLog |             ${message} |       True |     65.6065 ns |   0.6398 ns |  34.88 |          0.47 | 0.0135 |      52 B |

**Comment by damianh** [comment]
Oh nice! Thanks for the contrib :)

Sorry for delay, was waiting for #125.. I believe I can do a release soon.

**Comment by snakefoot** [comment]
@damianh Excellent. Have now applied the same trick for log4net. See #145

**Pull request merged**
