### PR TITLE
let LibLog be used by netstandard11 libs (the future of portable)

### PR DESCRIPTION
**Pull request by tofutim**
Please consider this.

https://github.com/damianh/LibLog/issues/124

### CODE REVIEW

**Comment by tofutim** [comment]
Note: for this to work, you must add the Conditional Compilation symbol LIBLOG_PORTABLE

image

**Comment by damianh** [comment]
Hi, thanks for PR.

I'm not going to do any dotnet core / netstandard work until the tooling churn has calmed down. Hopefully soon.

**Comment by tofutim** [comment]
This modification changes the log4net call to call GetLogger(Assembly, name) instead of GetLogger(name) which is not present in netstandard13 in log4net.

**Comment by damianh** [comment]
@tofutim why did you close this PR?

**Comment by tofutim** [comment]
I can re-open. Just got discouraged.

**Comment by damianh** [comment]
Sorry about the discouragement. I've a load of personal stuff going on atm and was waiting for VS2017 RTM for jumping into this.

I've pulled your PR and built the package. However when I install it into a netstandard1.4 project it can't resolve `LogProvider`

image

Are you sure this definitely worked for you? Do you have sample project you could upload that compiles?

**Comment by damianh** [comment]
This is encouraging - a least there is an entry in `obj/Debug/project.assets.json`:

image

**Comment by damianh** [comment]
http://stackoverflow.com/questions/35985232/nuget-3-3-contentfiles-not-added-to-project?answertab=active#comment70158197_36568001

Well, I'm in the same place @tofutim :)

**Comment by damianh** [comment]
>  path of the extracted files has the following schema: \obj\<Debug or Release>\NuGet\<some GUID>\<NuGet package name>\<version>\

This is not happening, and I don't know why.

image

Nothing of interest in the build log other than `Checking compatibility for LibLog 4.2.6-build00000 with .NETStandard,Version=v1.4.` at line 10.

[build.txt](https://github.com/damianh/LibLog/files/841079/build.txt)

**Comment by damianh** [comment]
Created an issue with nuget folks. https://github.com/NuGet/Home/issues/4803 As I'm at a complete dead end, I'm parking this until I get further info / insight.

**Comment by tofutim** [comment]
I'll take a look in a bit. I know it is working on this end. TM

**Comment by damianh** [comment]
I sincerely hope it's me being stupid :)

**Comment by damianh** [comment]
I've pulled your branch into https://github.com/damianh/LibLog/tree/loqu8-netstandard

**Comment by tofutim** [comment]
I recall running into this issue. I'm trying to figure out how I fixed it.

Are you using

<files>
<file src="LibLog.cs.pp" target="
content\App_Packages\LibLog.4.2\LibLog.cs.pp" />
<file src="LibLog.cs.pp" target="contentFiles\cs\any" />
<file src="LibLog.cs.pp" target="contentFiles\cs\netstandard1.1" />
</files>

**Comment by tofutim** [comment]
Wait, try upgrading to the latest version of nuget to see if it helps. I'll
keep thinking of what I did.

**Comment by tofutim** [comment]
I remember that I had an old version in my solution.

**Comment by tofutim** [comment]
And later an old version that was being used by TeamCity

**Comment by damianh** [comment]
Am out for a bit, and will be back online in a few hours

**Comment by damianh** [comment]
> I recall running into this issue. I'm trying to figure out how I fixed it.

> Are you using ...

I'm using exactly what you PR'd and just added a test solution to try out the package. VS2007 `install-package` is using nuget 4.0.0. I'm not sure this is a nuget concern given this issue https://github.com/dotnet/sdk/issues/577

**Comment by tofutim** [comment]
Damain, I am using nuget 3.5.0

**Comment by damianh** [comment]
Does nuget 3.5.0 do something special? It looks like an msbuild problem...

**Comment by tofutim** [comment]
I'll try to do some testing this afternoon to see why it works on this end.

**Comment by tofutim** [comment]
It definitely works on this end, but I had everything incremented to
netstandard13 and netstandard library 4.3, but I don't think that is
necessary. I should have written down what change I did.

**Comment by tofutim** [comment]
Damian,

My test class is netstandard13 and the LibLog.cs shows up in

D:\Loqu8\Server\kamelos\src\kamelos.Common\obj\Debug\NuGet\c7f0c99cefbb3407efab798374adacb8f973f89c\Loqu8.LibLog\4.2.9

I'll try netstandard14 and see if I get an issue.

**Comment by tofutim** [comment]
netstandard14 works
D:\Loqu8\Server\kamelos\src\kamelos.Common\obj\Debug\NuGet\c7f0c99cefbb3407efab798374adacb8f973f89c\Loqu8.LibLog\4.2.9

could it be a nuget 4.0 vs nuget 3.5 issue?

**Comment by damianh** [comment]
When you say you are using nuget.3.5 , how are exactly are you using it? VS Package Manager UI, command line or Powershell Package Manager? Could you upload your generated nupgk and zip up your test solution to here please? I'd like to get to the bottom of this. (Thanks for your help :)

**Comment by damianh** [comment]
@tofutim does this make any sense to you? https://github.com/NuGet/Home/issues/4803#issuecomment-286848526

**Comment by damianh** [comment]
Proof it's not working here:

animation

**Comment by damianh** [comment]
@tofutim Your package didn't work in VS2017 using `install-package` in Package Manager Console.

image

How **specifically** are you installing this package?

**Comment by damianh** [comment]
https://github.com/NuGet/Home/issues/2262#issuecomment-285134027

**Comment by tofutim** [comment]
I am using VS2015. Could that be the issue?

I just create a new portable class, change it to netstandard13, and then
add the nuget package.

**Comment by tofutim** [comment]
This netstandard/netcore/vs2017 will cost everyone a lot of time and money
I tell you.

**Comment by tofutim** [comment]
I am using project.json!

Sorry for the long confusion.

**Comment by tofutim** [comment]
That means also that I'm screwed if I update to VS2017. That is
discouraging.

**Comment by damianh** [comment]
Well that explains it so.

The new csproj handles packages differently to old "packages.config" way.
My reading indicates the content should be immutable and so transforms
won't work.

If so, this kills this PR and probably LibLog's current distribution
approach. (Project.json is dead too).

FFS.

**Comment by tofutim** [comment]
just kill it

hopefully you come up with a sln before i get to vs2017

**Comment by damianh** [comment]
Right and much flopping-about-in-the-wind I'm closing this as `won't fix`.

This is both unfortunate and disappointing. I have concluded that nuget won't be the channel for distributing and updating LibLog in NetStandard / NetCore projects. I'm going to have to think of something else. 

Couple of items I will look at:

 - [T4Include](https://github.com/mrange/T4Include)
 - [Packet](https://fsprojects.github.io/Paket/)
 - Some download (powershell/bash script) to pull from a URL
 - anything else suggested
 - combination of the above

Thanks loads for your patience @tofutim.

**Comment by tocsoft** [comment]
Can't you just provide a version that doesn't use the .pp type? instead provide a static .cs version?

Basically from what I can tell all the pp file is doing is allowing nuget to swap out the 'YourRootNamespace' namespace with that of the projects namespace... for netstandard can you just not allow that and hard code it to 'LibLog' for example? 

The library is most likely going to be used internal to a package so there's not likely to cause any namespace clashes (especially if you force the static one to internal only). If someone needs to tweek it more or make parts of it public etc then they could just grab the code manually from github and fill their boots.

**Comment by tofutim** [comment]
Currently I use a single library for a multi-library project and use
LIBLOG_PUBLIC. That works pretty well.

**Comment by damianh** [comment]
@tocsoft There is a definite public API aspect and hard coding the namespace to it to `LibLog` means two separate libs will introduce undesirable namespace clashing.

**Comment by damianh** [comment]
Some good news and bad. PP files are meant to be supported. https://github.com/dotnet/sdk/issues/70 . However there is a bug in VS2017 RTM / SDK that has been repro'd https://github.com/NuGet/Home/issues/4803#issuecomment-287649187 .

Re-opening this; I'm confident it will work (eventually).

**Comment by damianh** [comment]
@tofutim, going to close this. Work is happening in #149 . Cheers for kickstarting this!

**Pull request closed without merging**
