### PR TITLE
NLog MDLC + NDLC when NLog ver. 4.6 is ready

### PR DESCRIPTION
**Pull request by snakefoot**
NLog 4.6 includes better handling of non-string-objects: NLog/NLog#2857

### CODE REVIEW

**Comment by damianh** [comment]
Thanks for PR @snakefoot ! I see nlog 4.6 is not shipped yet. This is safe to ship before 4.6 is out?

**Comment by damianh** [comment]
@snakefoot Can you contact me privately (see my profile for email)? I would like some help maintaining this library and I feel I am doing a disservice to you and the lib's users at this point. Simple reason is time. Am @randompunter on twitter too if you want to DM there.

**Comment by snakefoot** [comment]
Yes the reflection logic will ensure the new logic will only activate when running with NLog 4.6

There might be a catch22 when having multiple libraries that are using LibLog and only some are using 5.0.3.Then use of OpenMdc will behave different during transition phase of upgrading all libraries. But MDLC is the "future".

I'm already fully booked with NLog so not ready for an extra child :)

Sent from my Sony Xperia


---- Damian Hickey wrote ----


Thanks for PR @snakefoot<https://github.com/snakefoot> ! I see nlog 4.6 is not shipped yet. This is safe to ship before 4.6 is out?

**Comment by snakefoot** [comment]
Should one also update the pp-file? Looks like I have forgotten it. Will fix it tonight. Unless you do it

Sent from my Sony Xperia


---- Damian Hickey wrote ----


Thanks for PR @snakefoot<https://github.com/snakefoot> ! I see nlog 4.6 is not shipped yet. This is safe to ship before 4.6 is out?

**Comment by snakefoot** [comment]
@damianh Created #188

**Pull request merged**
