### PR TITLE
Pass objects without toString conversion to Nlog MDC

### PR DESCRIPTION
**Pull request by andreyns**
OpenMappedContext method already accepts object values, but NLog and log4net implementations cast the values to strings
The PR removes the cast

@damianh please take a look

### CODE REVIEW

**Comment by snakefoot** [comment]
Usually one checks for the optimal-method, and if not available then it performs fallback. Now you have just replaced one with another without knowing which version has the new methods.

Also there can be dangers of writing non-string-objects into the CallContext of log4net.

**Comment by andreyns** [comment]
@snakefoot thanks for bringing. what is the minimum supported NLog version for liblog? and can you also share where the approach with optimal-method checks is used in liblog?

**Comment by snakefoot** [comment]
> thanks for bringing. what is the minimum supported NLog version for liblog? 

Not for me to investigate. I'm just stating the obvious.

**Comment by andreyns** [comment]
> As of NLog 4.1.1, the Mapped Diagnostics Context supports any Object type, not just String.
yes, you're right. I believe that is an acceptable limitation. @damianh what do you think?

**Comment by snakefoot** [comment]
Again AppDomains on IIS can throw random exception for complex objects saved to CallContext without ObjectHandle.

**Comment by andreyns** [comment]
if you're referring to the log4net issue, I can easily revert the change and keep the NLog piece only

**Comment by snakefoot** [comment]
>  @andreyns keep the NLog piece only

If you continue to write to MDC for NLog, then I have no objects against changing from string-value to object-value. But MDLC is needed for async-Task-context to work correctly.

**Comment by andreyns** [comment]
@damianh what do you think?

**Comment by snakefoot** [comment]
It is on purpose that NDLC + MDLC is not used for NLog 4.5 (Will work with Nlog 4.6). See also https://github.com/damianh/LibLog/issues/228#issuecomment-468928138

@damianh Guess this PR can be closed

**Comment by snakefoot** [comment]
@andreyns NLog 4.6 has now been released: https://www.nuget.org/packages/NLog.

Created #233 that updates the LibLog Test project.

So just update to NLog 4.6 and all your worries are over

**Comment by andreyns** [comment]
should I close the PR?

**Comment by snakefoot** [comment]
Fine by me. Unless you feel something is missing.


Sent from my Sony Xperia


---- Andrey Noskov wrote ----


should I close the PR?

**Pull request closed without merging**
