### PR TITLE
address all code analysis violations

### PR DESCRIPTION
**Pull request by adamralph**
What do you think?

### CODE REVIEW

**Comment by damianh** [comment]
Personally I don't use code analysis; got off that train a few years ago. But for this I can see how it is desirable so :+1:

**Comment by damianh** [comment]
@adamralph In general though, LibLog working out ok for you?

**Comment by adamralph** [comment]
@damianh thanks for merging!

> Personally I don't use code analysis; got off that train a few years ago.

I don't blame you. The CI story is appallingly broken and requires either a Work Of Art on the build agent or caving in and installing VS. I gave up on code analysis during CI a long time ago. However, for some projects we still run it as a manual step before release and fix any glaring issues.

> In general though, LibLog working out ok for you?

I can't claim to be a *heavy* user but generally it's working out well. IIRC we converted a couple of apps to use it in my previous job but since jumping ship 4 months ago the only thing I've used it in is scriptcs. We switched scriptcs to LibLog in 0.15, released at the beginning of August, and we've had no complaints. I'm currently in the process of switching ConfigR, which was what prompted me to send this PR.

**Comment by damianh** [comment]
Cool; thx for the feedback :)

**Pull request merged**
