### PR TITLE
Added support for Catel

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by damianh** [comment]
So I've never heard of Catel before and I went googlin'....

It looks like Catel isn't actually a logging framework...

From https://catelproject.atlassian.net/wiki/display/CTL/Logging

> Starting with version 2.2, Catel uses a custom internal logging system. This way, the reference to log4net could be removed. The idea behind this move is not to force the user to use log4net. Also, log4net seems deprecated (no new releases for a long time), and other logging systems such as NLog seem to grow in popularity.
The new logging system only allows very basic logging. This way, the logging is kept very simple and the real logging can be implemented by the end-developer if he/she feels the need for it.

Lovely. It looks like you've already done something that LibLog is designed to help with. That is, LibLog would be something you'd use **in** Catel rather than LibLog _supporting_ Catel's own abstractions. 

LibLog is only going to support actual logging frameworks people would use in end applications. As far as I can see, the recommendation is that someone using Catel would probably then also use Serilog / NLog etc. 

Similar to https://github.com/damianh/LibLog/wiki/Adapting%20LibLog%20to%20Microsoft.Owin.Logging , I think this work would be better represents as a gist on how to adapt Catel's logging abstraction to LibLog and vica versa. Thoughts?

**Comment by GeertvanHorrik** [comment]
That's correct. However, some basic stuff is implemented (such as ConsoleLogListener, FileLogListener, etc). One of the reasons I created this PR is that I replaced the reference to Catel.Core in GitTools.Core (a library we will use for several Git Tools). In some tools (the actual executables), we will still be using Catel and thus want to use Catel logging without having to link to another logging fx.

**Comment by kendallmiller** [comment]
I think you make a good point Damian; and a Gist may be a good solution for this.

**Comment by damianh** [comment]
@GeertvanHorrik Since Catel is not a logging framework so I'm not going to support it in LibLog. Remember, it'll be myself committing to long term maintenance of this if I were to pull it in. I've already prematurely made a mistake when prematurely pulling in the console logger #62 . 

LibLog's primary goal is to define a logging abstraction for libraries, like you have already done, so you are good. The logging _framework_ support is icing and not intended to other logging _abstractions_. A gist/wiki is best way forward for this imho.

Sorry, I know you put a bunch of work into this (perhaps opening an issue first would have been better though).

**Comment by GeertvanHorrik** [comment]
So coming back to this, I have a library that uses LibLog. Now I want to consume that using Catel. How should I write something like that?

**Pull request closed without merging**
