### PR TITLE
structured logging when using NLog 4.5 or upper

### LINKED ISSUE #239: support for structured logging when using NLog 4.5 or upper
something same to #45 
when using [NLog 4.5 or upper](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging) it will be support to use structured logging native.

I will a do some work on this and submit a PR.

### PR DESCRIPTION
**Pull request by newbe36524**
close #239

// Define LIBLOG_NLOG_STRUCTURED_LOGGING if you want to take advantage of structured logging in NLog 4.5 or upper.
// You can get more information about this feature in followed links:
// https://github.com/NLog/NLog/wiki/How-to-use-structured-logging
// https://github.com/damianh/LibLog/issues/239
// https://github.com/damianh/LibLog/issues/45

### CODE REVIEW

**Comment by snakefoot** [comment]
This is already supported in LibLog 5.0.3 (Be careful with using LibLog ver. 5.0.5 or newer until #233 has been merged).

Your PullRequest is targeting LibLog 4-branch.

**Comment by newbe36524** [comment]
> This is already supported in LibLog 5.0.3 (Be careful with using LibLog ver. 5.0.5 or newer until #233 has been merged).
> 
> Your PullRequest is targeting LibLog 4-branch.

is #233  will be merged into 4.x branch ?
I am using old csproj format.

**Comment by snakefoot** [comment]
@newbe36524 I would probably use this version (Coming from #145 + #142):

https://github.com/snakefoot/LibLog/blob/1362d476238d405eba01f11bba28e6a4d858773c/src/LibLog/LibLog.cs (Choose "Raw File" for copy-paste)

And just update your own copy of LibLog.cs.

**Comment by newbe36524** [comment]
> @newbe36524 I would probably use this version (Coming from #145 + #142):
> 
> https://github.com/snakefoot/LibLog/blob/1362d476238d405eba01f11bba28e6a4d858773c/src/LibLog/LibLog.cs (Choose "Raw" for copy-paste)
> 
> And just update your own copy of LibLog.cs.

It works, I would close this PR and copy your comment to #239

**Pull request closed without merging**
